spring.application.name=Md3-ss13

# Cấu hình datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_security
spring.datasource.username=postgres
spring.datasource.password=33333
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=MySecretKey123456789
jwt.expiration=86400000